import { StyleSheet } from "@react-pdf/renderer";
import { HEBREW_FONT_FAMILY } from "./fonts";

const styles = StyleSheet.create({
  page: {
    fontFamily: HEBREW_FONT_FAMILY,
    fontSize: 11,
    paddingTop: 40,
    paddingBottom: 60,
    paddingHorizontal: 40,
    direction: "rtl",
    textAlign: "right",
  },
  header: {
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    alignItems: "center",
    borderBottomWidth: 2,
    borderBottomColor: "#1a1a2e",
    paddingBottom: 10,
    marginBottom: 20,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: "#1a1a2e",
    textAlign: "right",
    direction: "rtl",
  },
  headerSubtitle: {
    fontSize: 9,
    color: "#555",
    textAlign: "right",
    direction: "rtl",
  },
  title: {
    fontSize: 18,
    fontWeight: 700,
    textAlign: "center",
    direction: "rtl",
    marginBottom: 16,
    color: "#1a1a2e",
  },
  subtitle: {
    fontSize: 14,
    fontWeight: 700,
    textAlign: "right",
    direction: "rtl",
    marginBottom: 8,
    marginTop: 14,
    color: "#1a1a2e",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    paddingBottom: 4,
  },
  body: {
    fontSize: 11,
    lineHeight: 1.8,
    textAlign: "right",
    direction: "rtl",
    color: "#222",
  },
  small: {
    fontSize: 9,
    textAlign: "right",
    direction: "rtl",
    color: "#666",
  },
  fieldHighlight: {
    fontWeight: 700,
    color: "#1a1a2e",
    textDecoration: "underline",
  },
  row: {
    flexDirection: "row-reverse",
    justifyContent: "flex-start",
    marginBottom: 4,
  },
  label: {
    fontSize: 11,
    fontWeight: 700,
    textAlign: "right",
    direction: "rtl",
    color: "#333",
    width: 120,
  },
  value: {
    fontSize: 11,
    textAlign: "right",
    direction: "rtl",
    color: "#111",
    flex: 1,
  },
  signatureArea: {
    borderWidth: 1,
    borderColor: "#999",
    borderStyle: "dashed",
    width: 200,
    height: 80,
    marginTop: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  signatureLabel: {
    fontSize: 9,
    color: "#888",
    textAlign: "center",
    direction: "rtl",
  },
  signatureImage: {
    width: 180,
    height: 60,
    objectFit: "contain",
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    flexDirection: "row-reverse",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#ddd",
    paddingTop: 6,
  },
  footerText: {
    fontSize: 8,
    color: "#999",
    textAlign: "right",
    direction: "rtl",
  },
  spacer: {
    height: 12,
  },
  checkboxRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    marginBottom: 4,
  },
  checkbox: {
    width: 12,
    height: 12,
    borderWidth: 1,
    borderColor: "#333",
    marginLeft: 6,
  },
  checkboxChecked: {
    width: 12,
    height: 12,
    borderWidth: 1,
    borderColor: "#333",
    backgroundColor: "#1a1a2e",
    marginLeft: 6,
  },
});

export { styles };
